CREATE TABLE IF NOT EXISTS CSV_DATE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FILE_NAME VARCHAR(255) NOT NULL,
    RECORD_DATA CLOB NOT NULL,
    PROCESSED_DATE TIMESTAMP NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FILE_PROCESSING_AUDIT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FILE_NAME VARCHAR(255) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    ERROR_MESSAGE VARCHAR(4000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CREATE INDEX IDX_CSV_FILE_NAME ON CSV_DATA(FILE_NAME);
-- CREATE INDEX IDX_CSV_PROCESSED_DATE ON CSV_DATA(PROCESSED_DATE);